#!/usr/bin/env bash
# WARNING: this script will destroy all data on the selected disk.
#
# graphical environment installed in bootstrap
#

mnt_pacman_need xorg-server xorg-xinit xorg-xrandr xautolock slock \
  i3-wm nitrogen brightnessctl gammastep arandr dunst libnotify xarchiver \
  libinput xf86-input-libinput xorg-xinput \
  archlinux-wallpaper elementary-wallpapers papirus-icon-theme flameshot \
  ttf-dejavu-emojiless ttf-liberation ttf-font-awesome ttf-hanazono ttf-hannom ttf-baekmuk \
  libreoffice-fresh nomacs krita smplayer evolution gnome-keyring \
  freerdp notepadqq gitg firefox keepassxc llpp pdfpc \
  pcmanfm ca-certificates ca-certificates-mozilla ca-certificates-utils \
  wine winetricks \
  p7zip-gui ttf-ms-fonts noto-fonts-emoji \
  xdg-desktop-portal xdg-desktop-portal-wlr \
  alacritty sysinfo
#mnt_pacman_need otf-openmoji
# corner coasting still not supported in libinput
# https://gitlab.freedesktop.org/libinput/libinput/-/issues/536
tee /mnt/usr/share/X11/xorg.conf.d/30-touchpad.conf <<EOF
Section "InputClass"
    Identifier "touchpad"
    Driver "libinput"
    MatchIsTouchpad "on"
    Option "ClickMethod" "clickfinger"
    Option "DisableWhileTyping" "on"
    Option "HorizontalScrolling" "on"
    Option "NaturalScrolling" "off"
    Option "Tapping" "on"
    Option "TappingButtonMap" "lrm"
    Option "TappingDrag" "on"
    Option "TappingDragLock" "on"
    Option "ScrollMethod" "twofinger"
EndSection
EOF

# configure firefox
mnt_pacman_need firefox-adguard firefox-forgetmenot firefox-singlefile firefox-keepassxc firefox-sponsorblock
mnt_cmd update-ca-trust
# https[://]support[.]mozilla[.]org/en-US/kb/customizing-firefox-using-autoconfig
tee /mnt/usr/lib/firefox/defaults/pref/autoconfig.js <<EOF
pref("general.config.filename", "firefox.cfg");
pref("general.config.obscure_value", 0);
EOF
chmod 0644 /mnt/usr/lib/firefox/defaults/pref/autoconfig.js
# https[://]github[.]com/arkenfox/user.js/blob/master/user.js
tee /mnt/usr/lib/firefox/firefox.cfg <<EOF
// IMPORTANT: Start your code on the 2nd line

lockPref("browser.preferences.defaultPerformanceSettings.enabled", false);
lockPref("layers.acceleration.force-enabled", true);
lockPref("layers.offmainthreadcomposition.enabled", true);
lockPref("gfx.webrender.all", true);
lockPref("media.hardware-video-decoding.force-enabled", true);
lockPref("media.hardwaremediakeys.enabled", true);
lockPref("browser.sessionstore.warnOnQuit", false);
lockPref("browser.startup.page", 3);
lockPref("widget.disable-workspace-management", true);
// font stuff
pref("browser.display.use_document_fonts", 0);
pref("font.name.serif.x-western", "Liberation Serif");
pref("font.name.sans-serif.x-western", "Liberation Sans");
pref("font.name.monospace.x-western", "Liberation Mono");
pref("font.minimum-size.x-western", 9);
lockPref("font.default.x-western", "Liberation Serif");
lockPref("font.name-list.emoji", "Noto Color Emoji");
// the user should not be able to display all passwords
lockPref("pref.privacy.disable_button.view_passwords", true);
lockPref("pref.privacy.disable_button.view_passwords_exceptions", true);
// disable advertising in newtab
pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
lockPref("browser.newtabpage.activity-stream.showSponsored", false);
lockPref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);
lockPref("browser.urlbar.sponsoredTopSites", false);
lockPref("services.sync.prefs.sync.browser.newtabpage.activity-stream.showSponsored", false);
lockPref("services.sync.prefs.sync.browser.newtabpage.activity-stream.showSponsoredTopSites", false);
pref("browser.newtabpage.activity-stream.topSitesRows", 2);
// disable telemetry
lockPref("datareporting.healthreport.uploadEnabled", false);
lockPref("datareporting.policy.dataSubmissionEnabled", false);
lockPref("toolkit.telemetry.newProfilePing.enabled", false);
lockPref("toolkit.telemetry.shutdownPingSender.enabled", false);
lockPref("toolkit.telemetry.updatePing.enabled", false);
lockPref("toolkit.telemetry.bhrPing.enabled", false);
lockPref("toolkit.telemetry.firstShutdownPing.enabled", false);
lockPref("toolkit.telemetry.archive.enabled", false);
lockPref("toolkit.telemetry.enabled", false);
lockPref("toolkit.telemetry.rejected", true);
lockPref("toolkit.telemetry.server", "data:,");
lockPref("toolkit.telemetry.unified", false);
lockPref("toolkit.telemetry.unifiedIsOptIn", false);
lockPref("toolkit.telemetry.prompted", 2);
lockPref("toolkit.telemetry.coverage.opt-out", true);
lockPref("toolkit.coverage.opt-out", true);
lockPref("toolkit.coverage.endpoint.base", "");
lockPref("browser.ping-centre.telemetry", false);
lockPref("app.shield.optoutstudies.enabled", false);
lockPref("app.normandy.enabled", false);
lockPref("app.normandy.api_url", "");
lockPref("toolkit.telemetry.pioneer-new-studies-available", false);
lockPref("breakpad.reportURL", "");
lockPref("browser.tabs.crashReporting.sendReport", false);
lockPref("browser.crashReports.unsubmittedCheck.enabled", false);
lockPref("browser.crashReports.unsubmittedCheck.autoSubmit2", false);
lockPref("browser.safebrowsing.downloads.remote.enabled", false);
lockPref("browser.safebrowsing.downloads.remote.url", "");
EOF
chmod 0644 /mnt/usr/lib/firefox/firefox.cfg

# https://github.com/stove-panini/fontconfig-emoji
# https://aur.archlinux.org/cgit/aur.git/tree/75-twemoji.conf?h=ttf-twemoji
tee /mnt/etc/fonts/conf.d/69-emoji.conf <<EOF
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <alias binding="weak">
    <family>sans-serif</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias binding="weak">
    <family>serif</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias binding="weak">
    <family>monospace</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias binding="weak">
    <family>DejaVu Sans</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias binding="weak">
    <family>DejaVu Serif</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias binding="weak">
    <family>DejaVu Sans Mono</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <match target="scan">
    <test name="family" compare="not_contains">
      <string>Font Awesome</string>
    </test>
    <edit name="charset" mode="assign">
      <minus>
        <name>charset</name>
        <charset>
          <range>
            <int>0xe000</int>
            <int>0xf8ff</int>
          </range>
        </charset>
      </minus>
    </edit>
  </match>
</fontconfig>
EOF
tee /mnt/etc/fonts/conf.d/70-no-mozilla-emoji.conf <<EOF
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <selectfont>
    <rejectfont>
      <pattern>
        <patelt name="family">
          <string>EmojiOne Mozilla</string>
        </patelt>
      </pattern>
      <pattern>
        <patelt name="family">
          <string>Twemoji Mozilla</string>
        </patelt>
      </pattern>
    </rejectfont>
  </selectfont>
</fontconfig>
EOF
#tee /mnt/etc/fonts/conf.d/70-no-openmoji-black.conf <<EOF
#<?xml version="1.0"?>
#<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
#<fontconfig>
#  <selectfont>
#    <rejectfont>
#      <pattern>
#        <patelt name="family">
#          <string>OpenMoji</string>
#        </patelt>
#        <patelt name="style">
#          <string>Black</string>
#        </patelt>
#      </pattern>
#    </rejectfont>
#  </selectfont>
#</fontconfig>
#EOF
tee /mnt/etc/fonts/conf.d/70-no-fa-regular.conf <<EOF
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <selectfont>
    <rejectfont>
      <pattern>
        <patelt name="family">
          <string>Font Awesome 5 Free</string>
        </patelt>
        <patelt name="style">
          <string>Regular</string>
        </patelt>
      </pattern>
    </rejectfont>
  </selectfont>
</fontconfig>
EOF
mnt_cmd fc-cache -f -v

# enable rdp
mnt_pacman_need xrdp
# not needed for wayland
# mnt_cmd systemctl enable xrdp xrdp-sesman
sed -i 's/^# exec xterm/exec \/bin\/bash --login -i ~\/.xinitrc/' /mnt/etc/xrdp/startwm.sh

### set regionals for target system ###
tee /mnt/usr/share/X11/xorg.conf.d/00-keyboard.conf <<EOF
Section "InputClass"
    Identifier "system-keyboard"
    Driver "libinput"
    MatchIsKeyboard "on"
    Option "XkbLayout" "de"
    Option "XkbModel" "pc105"
    Option "XkbVariant" "nodeadkeys"
EndSection
EOF

### road to wayland
mnt_pacman_need sway swayidle swaylock wdisplays wloutput xorg-xwayland foot
